### ISSUE TITLE
Not Really 3 Easy Steps?

### ISSUE THREAD

**Issue by ndumais** [gilzoide/unity-camera-viewport-rect#1]
Hey, first of all I really like the idea of this!
I've been trying to make this work outside of the demo scene without luck after trying to use this in my own project.

Repro:
1. Create a new scene
2. Add a second camera and a 3d object in front of it so it has something to display
3. Add a canvas Camera or Overlay and create a child rect, or a child in a child to put your component in
4. Assign a camera to your component

Also, I always try to add RawImages to some elements to make sure they actually show up, they do, just not the Viewport
Have you tried setting it up from an empty scene?

**Edit:** Just realized hiding the panel in hierarchy wont hide the render, only at runtime. Was using that a lot in testing so maybe that's why I couldn't get it to work

**Comment by ndumais** [comment]
Nevermind, it works! It might be helpful to add a brief explanation in the README on how it works. I expected a UI element, but it looks like it's just cameras drawing over other elements. Works great though, thanks for this!

**Comment by ndumais** [comment]
Made with your package

![image](https://github.com/user-attachments/assets/f2c83624-7411-47b5-9501-0519545b7971)

**Comment by gilzoide** [comment]
Hey @ndumais, thanks for the report, sorry it took me this long to get back to you.

I agree there's little explanation on how it works. The saying "without the need of setting up RenderTextures." implies that no RenderTextures are used, so no RawImages necessary. And the GIF shows the Camera's "Viewport Rect" being modified automatically, which implies that it's just the Viewport Rect that is adjusting to the RectTransform. That last bit assumes people have seen the GIF *and* know about Camera's Viewport, though 😅 Documentation could be much better indeed.

Glad you were able to use it successfully!
Cheers \o/
